image:
  repository: arsr319
  tag: "1.0.0"

dashboard:
  replicas: 2
  image:
    tag: "1.0.2"
  failMode: "true"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

accounts-service:
  replicas: 1
  image:
    tag: ""
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

insurance-service:
  replicas: 1
  image:
    tag: ""
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

investments-service:
  replicas: 1
  image:
    tag: ""
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

loans-service:
  replicas: 1
  image:
    tag: ""
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
