apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: dashboard
    count: 3

images:
  - name: arsr319/finovra-dashboard
    newTag: "1.0.0"
