apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  replicas: {{ (index .Values "accounts-service").replicas }}
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: accounts-service
          image: "{{ .Values.image.repository }}/finovra-accounts-service:{{ (index .Values "accounts-service").image.tag | default .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: VERSION
              value: "{{ (index .Values "accounts-service").image.tag | default .Values.image.tag }}"
            - name: FAIL_MODE
              value: "false"
            - name: LATENCY_MS
              value: "0"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
          resources:
            {{- toYaml (index .Values "accounts-service").resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  selector:
    app: accounts-service
  ports:
    - port: 8000
      targetPort: 8000
