apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: finovra-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/<your-username>/gitops.git
        revision: main
        directories:
          - path: k8s/plain-manifests/*
          - path: k8s/plain-manifests/dashboard
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/<your-username>/gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: finovra-services
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true